language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
# command to run tests
script:
  - pip freeze
  - nosetests
